### PR TITLE
Created the test for EnergySourcePhase service object

### PR DESCRIPTION
**Pull request by josimardtm**
Created the test for EnergySourcePhase service object

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [PROJ-260 service.objects(BaseVoltage)-python-sdk](https://app.clickup.com/t/6929263/PROJ-260)

**Comment by kgreav** [comment]
Can you redo the commit as a signed commit? Run:

```
git commit --amend -s
git push --force
```

**Comment by josimardtm** [comment]
I tried to amend the commit and sing it off, I'm not sure if it worked

**Comment by kgreav** [comment]
it did, thankyou

**Pull request merged**
