### PR TITLE
Add energy source fields for protobuf 0.19.0b6

### PR DESCRIPTION
**Pull request by Lax125**
Signed-off-by: Marcus Koh <marcus.koh@zepben.com>

### CODE REVIEW

**Comment by Lax125** [comment]
Why oh why do I keep forgetting to update the changelog

**Comment by charlta** [comment]
I believe this should be using evolve-grpc v0.19.0b6 for the pipelines to pass

**Comment by Lax125** [comment]
- [ ] Merge [EWB-1069](https://github.com/zepben/evolve-sdk-python/pull/74) first

**Comment by Lax125** [comment]
Odd, my latest commit isn't showing up here. I remembered to sign it off, too.

**Review by charlta — CHANGES_REQUESTED** [review]

**Review by charlta — APPROVED** [review]

**Pull request merged**
