### PR TITLE
EWB-1523: Do not use switches when getting base voltage

### PR DESCRIPTION
**Pull request by Lax125**
Signed-off-by: Marcus Koh <marcus.koh@zepben.com>

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [EWB-1523 Fix bug where open switches are used for voltage](https://app.clickup.com/t/6929263/EWB-1523)

**Comment by roberto-marquez** [comment]
Hey @Lax125 did you figure out why did you have switches with different voltages on either side? given that doesn't happen in the field?
Happy for this change to go in but please add a test to prevent a regression in the future and an entry in the changelog saying that base voltages from switches are not used in anymore in the bus_branch creator or something along those lines.

**Review by roberto-marquez — CHANGES_REQUESTED** [review]
Hey @Lax125 did you figure out why did you have switches with different voltages on either side? given that doesn't happen in the field?
Happy for this change to go in but please add a test to prevent a regression in the future and an entry in the changelog saying that base voltages from switches are not used in anymore in the bus_branch creator or something along those lines.

**Comment by Lax125** [comment]
I was originally tasked with standardising LV voltages to something consistent in https://app.clickup.com/t/6929263/PROJ-2349, but in the middle of the hosting capacity project I learned from Adam that we should be modelling them at the rating they gave us with the tap changers effectively reducing them down to something closer to 400V. I'll add a comment in the changelog.

**Review by roberto-marquez — CHANGES_REQUESTED** [review]
Changes look good @Lax125 but it looks like the test/build fails looks to be an issue with the newly added tests.

**Review by roberto-marquez — APPROVED** [review]

**Pull request merged**
