### PR TITLE
Proj 1990: Rewrite grpc connection code

### PR DESCRIPTION
**Pull request by Lax125**

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [PROJ-1990 Fix python sdk](https://app.clickup.com/t/6929263/PROJ-1990)

**Comment by Lax125** [comment]
Will need to copy old connect functions back in and mark them as deprecated.

**Comment by Lax125** [comment]
- [ ] Accept https://github.com/zepben/zepben-auth-python/pull/5 for checks to pass

**Comment by Lax125** [comment]
I know what the problem is: https://github.com/zepben/evolve-sdk-python/blob/762c4e6a64903e0c7e0cf273e767110433ae2bb2/test/streaming/get/test_network_consumer.py#L39
This needs to be a `grpc.aio.Channel`, not a `grpc.Channel`.

**Review by kgreav — CHANGES_REQUESTED** [review]
plz remove all the added versioned docs - they shouldn't be in here

**Review by charlta — APPROVED** [review]
Quick review only, nothing looks totally stupid/misformed to me but I am not familiar with the codebase so may have missed stuff which can just be fixed as new tasks if required.

**Pull request merged**
